name: test_dart_console
description: A simple test app for dart features.
version: 1.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dartz: 0.9.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
